### ISSUE TITLE
Only reads the first msg.

### ISSUE THREAD

**Issue by gurunave** [mukesh4u/NotificationListener#1]
Only reads the first msg.
how can I achieve to read all messages ?

**Comment by mukesh4u** [comment]
Hello, 
add below code which helps you to read second
notifcation text or evrey message one by one:

String text = null;
if (extras.getCharSequence("android.text") != null) {
text = extras.getCharSequence("android.text").toString();
}
if (text == null) {
// for whatsapp on kitkat second whats app text 
// will be null
if (extras.get("android.textLines") != null) {
CharSequence[] charText = (CharSequence[]) extras
.get("android.textLines");
if (charText.length > 0) {
text = charText[charText.length - 1].toString();
}
}
} - See more at: http://www.androiddevelopersolutions.com/2015/05/android-read-status-bar-notification.html#sthash.6bj5rC2z.dpuf
